### PR TITLE
FR vs random

### PR DESCRIPTION
**Pull request by josh-marsh**
This change is [Reviewable](https://reviewable.io/reviews/matthewja/thursday/36)

### CODE REVIEW

**Comment by MatthewJA** [comment]
Looks pretty good! Just a few things to fix up.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[thursday/experiments.py, line 29 at r1](https://reviewable.io/reviews/matthewja/thursday/36#-LAyqMmU7wEmH4WLSOli:-LAyqMmU7wEmH4WLSOlj:b-wrfx2m) ([raw file](https://github.com/matthewja/thursday/blob/9b23bb284c98edb8de1d519cb8c2ecea488b31b4/thursday/experiments.py#L29)):*
Use either `os.path.join` to combine paths like this, *or* use the hip new module [`pathlib`](https://docs.python.org/3/library/pathlib.html#concrete-paths).

```python3
>>> p = Path('/etc')
>>> p
PosixPath('/etc')
>>> p / 'init.d' / 'apache2'
PosixPath('/etc/init.d/apache2')
```

Since you're using `pathlib` anyway, use it consistently!

---

*[thursday/experiments.py, line 114 at r1](https://reviewable.io/reviews/matthewja/thursday/36#-LAyr3CcBXKgLq9L9iB-:-LAyr3CcBXKgLq9L9iB0:br9czem) ([raw file](https://github.com/matthewja/thursday/blob/9b23bb284c98edb8de1d519cb8c2ecea488b31b4/thursday/experiments.py#L114)):*
> ```Python
>     predictions = classifier.predict(test_x)
> 
>     print (predictions)
> ```

Make sure your prints have some text associated with them.

---

*[thursday/experiments.py, line 117 at r1](https://reviewable.io/reviews/matthewja/thursday/36#-LAyr8bY27CCnP7KQF-F:-LAyr8bY27CCnP7KQF-G:b3dxtqo) ([raw file](https://github.com/matthewja/thursday/blob/9b23bb284c98edb8de1d519cb8c2ecea488b31b4/thursday/experiments.py#L117)):*
> ```Python
> 
>     correct = test_y == predictions
>     print('Accuracy: {:.02%}'.format(correct.mean()))
> ```

Also print what classifier we have (otherwise we'll just be seeing an accuracy with no context)

---

*[thursday/format_data.py, line 211 at r1](https://reviewable.io/reviews/matthewja/thursday/36#-LAyrIn-2_T9Qvb_3laX:-LAyrIn-2_T9Qvb_3laY:b-5kyieg) ([raw file](https://github.com/matthewja/thursday/blob/9b23bb284c98edb8de1d519cb8c2ecea488b31b4/thursday/format_data.py#L211)):*
> ```Python
>    
>    return datagen
> ```

Two newlines

---

*[thursday/format_data.py, line 261 at r1](https://reviewable.io/reviews/matthewja/thursday/36#-LAyrOHgBnemGR2ey7wn:-LAyrOHgBnemGR2ey7wo:bupy75j) ([raw file](https://github.com/matthewja/thursday/blob/9b23bb284c98edb8de1d519cb8c2ecea488b31b4/thursday/format_data.py#L261)):*
> ```Python
>    
>    return x
> ```

Two newlines... and so on.

(only in top-level functions — not in class methods)

---

*[thursday/format_data.py, line 454 at r1](https://reviewable.io/reviews/matthewja/thursday/36#-LAyrW4OELq5wORSq2un:-LAyrW4OELq5wORSq2uo:bxlf4da) ([raw file](https://github.com/matthewja/thursday/blob/9b23bb284c98edb8de1d519cb8c2ecea488b31b4/thursday/format_data.py#L454)):*
> ```Python
>    test = labels[test_i]
> 
>    train_y = np.where(train == 2, True, False)
> ```

This is equivalent to `train == 2`

---

*[thursday/data/asu.tsv, line 0 at r1](https://reviewable.io/reviews/matthewja/thursday/36#-LAyrb6pC3PTZuBG-xkF:-LAyrb6pC3PTZuBG-xkG:b-o7ea6u) ([raw file](https://github.com/matthewja/thursday/blob/9b23bb284c98edb8de1d519cb8c2ecea488b31b4/thursday/data/asu.tsv#L0)):*
Don't commit this file

---


*Comments from [Reviewable](https://reviewable.io/reviews/matthewja/thursday/36#-:-LAyrgHt7rewXI8XYiwm:b-2k2eyw)*

**Comment by josh-marsh** [comment]
*[thursday/data/asu.tsv, line  at r1](https://reviewable.io/reviews/matthewja/thursday/36#-LAyrb6pC3PTZuBG-xkF:-LAzRwt_AJB65bBBaTnh:bj09la) ([raw file](https://github.com/matthewja/thursday/blob/9b23bb284c98edb8de1d519cb8c2ecea488b31b4/thursday/data/asu.tsv#L)):*
<details><summary><i>Previously, MatthewJA (Matthew Alger) wrote…</i></summary><blockquote>

Don't commit this file
</blockquote></details>

But don't they need it?

---


*Comments from [Reviewable](https://reviewable.io/reviews/matthewja/thursday/36)*

**Comment by josh-marsh** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[thursday/experiments.py, line 29 at r1](https://reviewable.io/reviews/matthewja/thursday/36#-LAyqMmU7wEmH4WLSOli:-LAzNsOwCDgU4Le85sNt:bs7wumb) ([raw file](https://github.com/matthewja/thursday/blob/9b23bb284c98edb8de1d519cb8c2ecea488b31b4/thursday/experiments.py#L29)):*
<details><summary><i>Previously, MatthewJA (Matthew Alger) wrote…</i></summary><blockquote>

Use either `os.path.join` to combine paths like this, *or* use the hip new module [`pathlib`](https://docs.python.org/3/library/pathlib.html#concrete-paths).

```python3
>>> p = Path('/etc')
>>> p
PosixPath('/etc')
>>> p / 'init.d' / 'apache2'
PosixPath('/etc/init.d/apache2')
```

Since you're using `pathlib` anyway, use it consistently!
</blockquote></details>

Done.

---

*[thursday/experiments.py, line 114 at r1](https://reviewable.io/reviews/matthewja/thursday/36#-LAyr3CcBXKgLq9L9iB-:-LAzQq6fB-ElijYOW_3W:bs7wumb) ([raw file](https://github.com/matthewja/thursday/blob/9b23bb284c98edb8de1d519cb8c2ecea488b31b4/thursday/experiments.py#L114)):*
<details><summary><i>Previously, MatthewJA (Matthew Alger) wrote…</i></summary><blockquote>

Make sure your prints have some text associated with them.
</blockquote></details>

Done.

---

*[thursday/experiments.py, line 117 at r1](https://reviewable.io/reviews/matthewja/thursday/36#-LAyr8bY27CCnP7KQF-F:-LAzT5309nAcqdXeznDB:bb7f2mf) ([raw file](https://github.com/matthewja/thursday/blob/9b23bb284c98edb8de1d519cb8c2ecea488b31b4/thursday/experiments.py#L117)):*
<details><summary><i>Previously, MatthewJA (Matthew Alger) wrote…</i></summary><blockquote>

Also print what classifier we have (otherwise we'll just be seeing an accuracy with no context)
</blockquote></details>

done

---

*[thursday/format_data.py, line 211 at r1](https://reviewable.io/reviews/matthewja/thursday/36#-LAyrIn-2_T9Qvb_3laX:-LAzT3o700Kcq6oCPc_M:b32wtd) ([raw file](https://github.com/matthewja/thursday/blob/9b23bb284c98edb8de1d519cb8c2ecea488b31b4/thursday/format_data.py#L211)):*
<details><summary><i>Previously, MatthewJA (Matthew Alger) wrote…</i></summary><blockquote>

Two newlines
</blockquote></details>

ok

---

*[thursday/format_data.py, line 261 at r1](https://reviewable.io/reviews/matthewja/thursday/36#-LAyrOHgBnemGR2ey7wn:-LAzT0sI4d46jAC0vZ1v:b2ni9b3) ([raw file](https://github.com/matthewja/thursday/blob/9b23bb284c98edb8de1d519cb8c2ecea488b31b4/thursday/format_data.py#L261)):*
<details><summary><i>Previously, MatthewJA (Matthew Alger) wrote…</i></summary><blockquote>

Two newlines... and so on.

(only in top-level functions — not in class methods)
</blockquote></details>

ok 

---

*[thursday/format_data.py, line 454 at r1](https://reviewable.io/reviews/matthewja/thursday/36#-LAyrW4OELq5wORSq2un:-LAzS_I97DFQ59X3K0pb:b-d3lemw) ([raw file](https://github.com/matthewja/thursday/blob/9b23bb284c98edb8de1d519cb8c2ecea488b31b4/thursday/format_data.py#L454)):*
<details><summary><i>Previously, MatthewJA (Matthew Alger) wrote…</i></summary><blockquote>

This is equivalent to `train == 2`
</blockquote></details>

That just returns the indices where train==2

---


*Comments from [Reviewable](https://reviewable.io/reviews/matthewja/thursday/36)*

**Comment by josh-marsh** [comment]
Fixed. See comments for divergences.

---

Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/matthewja/thursday/36#-:-LAzT7ze1kfqfe49xti6:b-m91jy4)*

**Comment by MatthewJA** [comment]
Few more fixes (some fixes don't seem to be pushed)

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[thursday/experiments.py, line 114 at r1](https://reviewable.io/reviews/matthewja/thursday/36#-LAyr3CcBXKgLq9L9iB-:-LAzV3rk0QEHtxKDoN0D:br0nc2) ([raw file](https://github.com/matthewja/thursday/blob/9b23bb284c98edb8de1d519cb8c2ecea488b31b4/thursday/experiments.py#L114)):*
<details><summary><i>Previously, josh-marsh wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It doesn't seem to be done in this commit.

---

*[thursday/experiments.py, line 117 at r1](https://reviewable.io/reviews/matthewja/thursday/36#-LAyr8bY27CCnP7KQF-F:-LAzV6kf6B9fGejo005Z:b-8a05gs) ([raw file](https://github.com/matthewja/thursday/blob/9b23bb284c98edb8de1d519cb8c2ecea488b31b4/thursday/experiments.py#L117)):*
<details><summary><i>Previously, josh-marsh wrote…</i></summary><blockquote>

done
</blockquote></details>

As above

---

*[thursday/format_data.py, line 454 at r1](https://reviewable.io/reviews/matthewja/thursday/36#-LAyrW4OELq5wORSq2un:-LAzVNvE3WXT__m-JryN:bchydnp) ([raw file](https://github.com/matthewja/thursday/blob/9b23bb284c98edb8de1d519cb8c2ecea488b31b4/thursday/format_data.py#L454)):*
<details><summary><i>Previously, josh-marsh wrote…</i></summary><blockquote>

That just returns the indices where train==2
</blockquote></details>

No it doesn't. It returns a boolean array.

---

*[thursday/format_data.py, line 179 at r2](https://reviewable.io/reviews/matthewja/thursday/36#-LAzVF8R7HOFQ2pOBwkf:-LAzVF8R7HOFQ2pOBwkg:b32w41) ([raw file](https://github.com/matthewja/thursday/blob/2e396a92de53a31fd9d122283fc3c0545ae8b828/thursday/format_data.py#L179)):*
> ```Python
>        """
>       image += 10e-10 * np.random.randn(image.shape[0], image.shape[1], 1)
>       S
> ```

S?

---

*[thursday/data/asu.tsv, line  at r1](https://reviewable.io/reviews/matthewja/thursday/36#-LAyrb6pC3PTZuBG-xkF:-LAzVS_W04b6JXTZXAWS:b-99vmbb) ([raw file](https://github.com/matthewja/thursday/blob/9b23bb284c98edb8de1d519cb8c2ecea488b31b4/thursday/data/asu.tsv#L)):*
<details><summary><i>Previously, josh-marsh wrote…</i></summary><blockquote>

But don't they need it?
</blockquote></details>

They can download it from VizieR.

---


*Comments from [Reviewable](https://reviewable.io/reviews/matthewja/thursday/36#-:-LAzVXPND_zrX-BJsdIa:b-k2h04i)*

**Comment by josh-marsh** [comment]
Review status: 4 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[thursday/experiments.py, line 114 at r1](https://reviewable.io/reviews/matthewja/thursday/36#-LAyr3CcBXKgLq9L9iB-:-LAzhn334sliVIbBB-2x:b-na8l62) ([raw file](https://github.com/matthewja/thursday/blob/9b23bb284c98edb8de1d519cb8c2ecea488b31b4/thursday/experiments.py#L114)):*
<details><summary><i>Previously, MatthewJA (Matthew Alger) wrote…</i></summary><blockquote>

It doesn't seem to be done in this commit.
</blockquote></details>

my bad

---

*[thursday/format_data.py, line 454 at r1](https://reviewable.io/reviews/matthewja/thursday/36#-LAyrW4OELq5wORSq2un:-LAzh1BVAiTA0S4bI5Ri:b-nckm0q) ([raw file](https://github.com/matthewja/thursday/blob/9b23bb284c98edb8de1d519cb8c2ecea488b31b4/thursday/format_data.py#L454)):*
<details><summary><i>Previously, MatthewJA (Matthew Alger) wrote…</i></summary><blockquote>

No it doesn't. It returns a boolean array.
</blockquote></details>

Oh my bad, I thought you meant np.where(train == 2). Should I not be consistent?

---

*[thursday/format_data.py, line 179 at r2](https://reviewable.io/reviews/matthewja/thursday/36#-LAzVF8R7HOFQ2pOBwkf:-LAzfzoL0s7VqtltVO4c:bgruc90) ([raw file](https://github.com/matthewja/thursday/blob/2e396a92de53a31fd9d122283fc3c0545ae8b828/thursday/format_data.py#L179)):*
<details><summary><i>Previously, MatthewJA (Matthew Alger) wrote…</i></summary><blockquote>

S?
</blockquote></details>

Don't ask

---

*[thursday/data/asu.tsv, line  at r1](https://reviewable.io/reviews/matthewja/thursday/36#-LAyrb6pC3PTZuBG-xkF:-LAzg1DQ5AVSiebKu8HQ:b32wtd) ([raw file](https://github.com/matthewja/thursday/blob/9b23bb284c98edb8de1d519cb8c2ecea488b31b4/thursday/data/asu.tsv#L)):*
<details><summary><i>Previously, MatthewJA (Matthew Alger) wrote…</i></summary><blockquote>

They can download it from VizieR.
</blockquote></details>

ok

---


*Comments from [Reviewable](https://reviewable.io/reviews/matthewja/thursday/36)*

**Comment by josh-marsh** [comment]
Pushed

---

Review status: 4 of 6 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/matthewja/thursday/36#-:-LAziccg3qRTsn-E6wyT:bxzudge)*

**Comment by josh-marsh** [comment]
Review status: 4 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[thursday/experiments.py, line 117 at r1](https://reviewable.io/reviews/matthewja/thursday/36#-LAyr8bY27CCnP7KQF-F:-LAzilsL7A822-v_T-li:bb7f2mf) ([raw file](https://github.com/matthewja/thursday/blob/9b23bb284c98edb8de1d519cb8c2ecea488b31b4/thursday/experiments.py#L117)):*
<details><summary><i>Previously, MatthewJA (Matthew Alger) wrote…</i></summary><blockquote>

As above
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io/reviews/matthewja/thursday/36)*

**Comment by MatthewJA** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[thursday/format_data.py, line 454 at r1](https://reviewable.io/reviews/matthewja/thursday/36#-LAyrW4OELq5wORSq2un:-LAzjTBS2fX6m6zsd_70:bw78bp5) ([raw file](https://github.com/matthewja/thursday/blob/9b23bb284c98edb8de1d519cb8c2ecea488b31b4/thursday/format_data.py#L454)):*
<details><summary><i>Previously, josh-marsh wrote…</i></summary><blockquote>

Oh my bad, I thought you meant np.where(train == 2). Should I not be consistent?
</blockquote></details>

Be consistent and don't use where, unless you need it

---


*Comments from [Reviewable](https://reviewable.io/reviews/matthewja/thursday/36#-:-LAzjYrH1rQ8xcGYw2hE:bnfp4nl)*

**Pull request merged**
